version: 2
jobs:
 build:
  docker:
   - image: circleci/ruby:2.4.1
  steps:
   - checkout
   - run: echo "Say hello from build world"
 test:
  docker:
   - image: circleci/ruby:2.4.1
  steps:
   - checkout
   - run:
      name: Testing Message
      command: echo "Hello from testing world!"
workflows:
 version: 2
 build_and_test:
 jobs:
  - build
  - test:
     requires:
      - build
					